---
title: "Zero-Copy Integration"
subtitle: "Architecture for the Fragmented Enterprise"
author: "Alan Hamilton"
date: "2026"
lang: en-GB
rights: "CC BY-SA 4.0"
toc: true
toc-depth: 2
numbersections: false
---
